eureka:
  instance:
#    hostname: discovery-service
    prefer-ip-address: true
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka/


# To check whether the service is up by accessing the actuator
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  metrics:
    tags:
      application: ${spring.application.name}
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: ${spring.application.name}

spring:
  cloud:
    config:
      override.system-properties: false

app:
  keycloak:
    realm: micro-services
    authorization_url: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    token_url: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  gateway-url: http://localhost:8222