eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    renewal-percent-threshold: 0.85

spring:
  # To know where to validate JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use the container name 'keycloak-ms' as defined in your docker-compose
          issuer-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}
          # Jars might need this if they can't reach the issuer during startup
          jwk-set-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs


server:
  port: 8761