spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20        # standard 10
      minimum-idle: 10             # keep connections warm
      connection-timeout: 3000     # fail fast if no connection in 3s
      idle-timeout: 600000         # 10 mins idle before closing
      max-lifetime: 1800000        # 30 mins max connection lifetime
      pool-name: HikariPool-${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_size: 30
  kafka:
    bootstrap-servers: kafka:29092
    template:
      order-topic: order-topic
      payment-topic: payment-topic
      payment-success-topic: payment-success-topic
      payment-failure-topic: payment-failure-topic
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          paymentCompletionEvent:com.example.ecomerce.kafka.payment.PaymentSuccessEvent,
          paymentFailureEvent:com.example.ecomerce.kafka.payment.PaymentFailureEvent
        spring.json.trusted.packages: '*'
    consumer:
      #      group-id: orderGroup
      auto-offset-reset: earliest
      bootstrap-servers: kafka:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # inner deserializer that does the actual work
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        #  Tells the consumer what kind of object it should expect, where the obj is coming from, what object to trust / consume
        spring.json.type.mapping: >
          paymentSuccessEvent:com.example.ecomerce.kafka.payment.PaymentSuccessEvent,
          paymentFailureEvent:com.example.ecomerce.kafka.payment.PaymentFailureEvent
        spring.json.trusted.packages: '*'

  # To know where to validate JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use the container name 'keycloak-ms' as defined in your docker-compose
          issuer-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}
          # Jars might need this if they can't reach the issuer during startup
          jwk-set-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

  threads:
    virtual:
      enabled: true


server:
  port: 8070
  forward-headers-strategy: framework

application:
  config:
    customer-url: http://customer-service:8090/api/v1/customers
    product-url: http://product-service:8050/api/v1/products
    payment-url: http://payment-service:8060/api/v1/payments