spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/products
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20        # standard 10
      minimum-idle: 10             # keep connections warm
      connection-timeout: 3000     # fail fast if no connection in 3s
      idle-timeout: 600000         # 10 mins idle before closing
      max-lifetime: 1800000        # 30 mins max connection lifetime
      pool-name: HikariPool-${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000        # 5 minutes
      cache-null-values: false
  # To know where to validate JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use the container name 'keycloak-ms' as defined in your docker-compose
          issuer-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}
          # Jars might need this if they can't reach the issuer during startup
          jwk-set-uri: http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

#springdoc:
#  swagger-ui:
#    oauth2-redirect-url: http://localhost:${server.port}/swagger-ui/oauth2-redirect.html

server:
  port: 8050