server:
  port: 8888

spring:
  application:
    name: config-sv
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/${SOURCE_FOLDER:dev}
  config:
    activate:
      on-profile: native
    import: optional:file:../../.env[.properties]