server:
  port: 8888

spring:
  application:
    name: config-sv
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/dev
  config:
    import: optional:file:../../.env[.properties]