CREATE TABLE payment (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     amount NUMERIC(38, 2),
     payment_method VARCHAR(255),
     order_id BIGINT,
     created_date TIMESTAMP NOT NULL,
     last_modified_date TIMESTAMP,
     CONSTRAINT uk_payment_orderId UNIQUE (order_id)
);

CREATE TABLE outbox_event (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      event_type VARCHAR(255) NOT NULL,
      payload JSONB NOT NULL,
      published BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMP NOT NULL DEFAULT now()
);