CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255),
    total_amount NUMERIC(38, 2),
    payment_method VARCHAR(255),
    status VARCHAR(255),
    customer_id VARCHAR(255),
    version BIGINT,
    created_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP
);

CREATE TABLE order_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    quantity DOUBLE PRECISION,
    unit_price NUMERIC(38, 2),
    CONSTRAINT fk_order_line_order FOREIGN KEY (order_id) REFERENCES customer_order (id)
);

CREATE TABLE outbox_event (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL,
    published BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE processed_event (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type VARCHAR(255),
    order_id BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT uk_processed_event_order_type UNIQUE (order_id, event_type)
);