eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# To check whether the service is up by accessing the actuator
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  metrics:
    tags:
      application: ${spring.application.name}
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3_multi
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: ${spring.application.name}


spring:
  cloud:
    config:
      override.system-properties: false

  # To know where to validate JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use the container name
          issuer-uri: http://localhost:8080/realms/${KEYCLOAK_REALM}
          # Jars might need this if they can't reach the issuer during startup
          jwk-set-uri: http://localhost:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    servers:
      - url: http://localhost:8222
        description: API Gateway

app:
  keycloak:
    realm: micro-services
    authorization_url: http://localhost:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    token_url: http://localhost:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  gateway-url: http://localhost:8222