eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# To check whether the service is up by accessing the actuator
management:
  endpoints:
    web:
      exposure:
        include: health


spring:
  cloud:
    config:
      override.system-properties: false

  # To know where to validate JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use the container name
          issuer-uri: http://localhost:9098/realms/${KEYCLOAK_REALM}
          # Jars might need this if they can't reach the issuer during startup
          jwk-set-uri: http://localhost:9098/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    servers:
      - url: http://localhost:8222
        description: API Gateway

app:
  keycloak:
    realm: micro-services-api
    authorization_url: http://localhost:9098/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    token_url: http://localhost:9098/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
