spring:
  mongodb:
    username: ${MONGO_ROOT_USER}
    password: ${MONGO_ROOT_PASSWORD}
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
  data:
    mongodb:
      auto-index-creation: true

server:
  port: 8090
  forward-headers-strategy: framework