server:
  port:
    8222

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
              lower-case-service-id: true
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**, /customer-service/**
              filters:
                - TokenRelay=
                #Se scoate prima bucata din url - /customer-service si se trimite doar /api/v3/api-docs mai departe catre service
                - RewritePath=/customer-service/(?<segment>.*), /$\{segment}
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**, /order-service/**
              filters:
                - TokenRelay=
                - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - id: order-lines-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order-lines/**
              filters:
                - TokenRelay=
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**, /product-service/**
              filters:
                - TokenRelay=
                - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**, /payment-service/**
              filters:
                - TokenRelay=
                - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

management:
#  tracing:
#    sampling:
#      probability: 1.0
#    export:
#      zipkin:
#        endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "gateway,health"
  endpoint:
    gateway:
      access: read_only

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE

springdoc:
  enable-native-support: true
  show-common-extensions: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: E-Commerce App
    urls:
      - name: Order Service
        url: /order-service/v3/api-docs
      - name: Product Service
        url: /product-service/v3/api-docs
      - name: Customer Service
        url: /customer-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
