spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20        # standard 10
      minimum-idle: 10             # keep connections warm
      connection-timeout: 3000     # fail fast if no connection in 3s
      idle-timeout: 600000         # 10 mins idle before closing
      max-lifetime: 1800000        # 30 mins max connection lifetime
      pool-name: HikariPool-${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_size: 30
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    template:
#      default-topic: order-topic
      order-topic: order-topic
      payment-topic: payment-topic
      payment-success-topic: payment-success-topic
      payment-failure-topic: payment-failure-topic
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.example.ecomerce.kafka.OrderConfirmation
    consumer:
      enable-auto-commit: false
#      group-id: orderGroup
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # inner deserializer that does the actual work
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        #  Tells the consumer what kind of object it should expect, where the obj is coming from, what object to trust / consume
        spring.json.type.mapping: >
          paymentSuccessEvent:com.example.ecomerce.kafka.payment.PaymentSuccessEvent,
          paymentFailureEvent:com.example.ecomerce.kafka.payment.PaymentFailureEvent
        spring.json.trusted.packages: '*'

  threads:
    virtual:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50          # open after 50% failures
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      productService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

server:
  port: 8070
  forward-headers-strategy: framework

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8050/api/v1/products
    payment-url: http://localhost:8060/api/v1/payments