spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-payment-service
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    template:
#      default-topic: payment-topic
      order-topic: order-topic
      payment-topic: payment-topic
      payment-success-topic: payment-success-topic
      payment-failure-topic: payment-failure-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentEvent:com.example.ecomerce.kafka.payment.PaymentEvent
    consumer:
#      group-id: orderGroup
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # inner deserializer that does the actual work
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        #        Tells the consumer what kind of object it should expect, where the obj is coming from, what object to trust / consume
        spring.json.type.mapping: paymentEvent:com.example.ecomerce.kafka.payment.PaymentEvent
        spring.json.trusted.packages: '*'

server:
  port: 8060
  forward-headers-strategy: framework