spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20        # standard 10
      minimum-idle: 10             # keep connections warm
      connection-timeout: 3000     # fail fast if no connection in 3s
      idle-timeout: 600000         # 10 mins idle before closing
      max-lifetime: 1800000        # 30 mins max connection lifetime
      pool-name: HikariPool-${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_size: 30
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000        # 5 minutes
      cache-null-values: false


#springdoc:
#  swagger-ui:
#    oauth2-redirect-url: http://localhost:${server.port}/swagger-ui/oauth2-redirect.html

server:
  port: 8050